# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GS_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroundStationSensorControl(object):
    def setupUi(self, GroundStationSensorControl):
        GroundStationSensorControl.setObjectName("GroundStationSensorControl")
        GroundStationSensorControl.resize(1894, 889)
        GroundStationSensorControl.setFocusPolicy(QtCore.Qt.WheelFocus)
        GroundStationSensorControl.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        GroundStationSensorControl.setAcceptDrops(False)
        GroundStationSensorControl.setModal(False)
        self.close = QtWidgets.QDialogButtonBox(GroundStationSensorControl)
        self.close.setGeometry(QtCore.QRect(1690, 820, 131, 41))
        self.close.setOrientation(QtCore.Qt.Horizontal)
        self.close.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.close.setObjectName("close")
        self.FPV_Feed = QtWidgets.QLabel(GroundStationSensorControl)
        self.FPV_Feed.setGeometry(QtCore.QRect(30, 130, 831, 721))
        self.FPV_Feed.setFrameShape(QtWidgets.QFrame.Box)
        self.FPV_Feed.setMidLineWidth(4)
        self.FPV_Feed.setText("")
        self.FPV_Feed.setObjectName("FPV_Feed")
        self.label = QtWidgets.QLabel(GroundStationSensorControl)
        self.label.setGeometry(QtCore.QRect(1090, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(GroundStationSensorControl)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 1251, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setLineWidth(3)
        self.label_2.setMidLineWidth(0)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.UAV_AT_Command_Line = QtWidgets.QLineEdit(GroundStationSensorControl)
        self.UAV_AT_Command_Line.setGeometry(QtCore.QRect(1310, 60, 551, 51))
        self.UAV_AT_Command_Line.setObjectName("UAV_AT_Command_Line")
        self.label_7 = QtWidgets.QLabel(GroundStationSensorControl)
        self.label_7.setGeometry(QtCore.QRect(1310, 20, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame = QtWidgets.QFrame(GroundStationSensorControl)
        self.frame.setGeometry(QtCore.QRect(880, 170, 191, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.EnableFPV = QtWidgets.QCheckBox(self.frame)
        self.EnableFPV.setObjectName("EnableFPV")
        self.gridLayout.addWidget(self.EnableFPV, 0, 0, 1, 1)
        self.EnableDatalogging = QtWidgets.QCheckBox(self.frame)
        self.EnableDatalogging.setObjectName("EnableDatalogging")
        self.gridLayout.addWidget(self.EnableDatalogging, 1, 0, 1, 1)
        self.Send_Commands = QtWidgets.QPushButton(GroundStationSensorControl)
        self.Send_Commands.setGeometry(QtCore.QRect(1310, 120, 551, 41))
        self.Send_Commands.setObjectName("Send_Commands")
        self.Command_Output = QtWidgets.QTextEdit(GroundStationSensorControl)
        self.Command_Output.setGeometry(QtCore.QRect(1313, 170, 551, 621))
        self.Command_Output.setReadOnly(True)
        self.Command_Output.setObjectName("Command_Output")
        self.label_8 = QtWidgets.QLabel(GroundStationSensorControl)
        self.label_8.setGeometry(QtCore.QRect(880, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.frame_2 = QtWidgets.QFrame(GroundStationSensorControl)
        self.frame_2.setGeometry(QtCore.QRect(1100, 170, 191, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Connect_Radio = QtWidgets.QPushButton(self.frame_2)
        self.Connect_Radio.setObjectName("Connect_Radio")
        self.gridLayout_2.addWidget(self.Connect_Radio, 2, 0, 1, 1)
        self.Refresh_Ports = QtWidgets.QPushButton(self.frame_2)
        self.Refresh_Ports.setObjectName("Refresh_Ports")
        self.gridLayout_2.addWidget(self.Refresh_Ports, 1, 0, 1, 1)
        self.COM_Select = QtWidgets.QComboBox(self.frame_2)
        self.COM_Select.setObjectName("COM_Select")
        self.gridLayout_2.addWidget(self.COM_Select, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(GroundStationSensorControl)
        self.frame_3.setGeometry(QtCore.QRect(880, 460, 411, 391))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Airspeed = QtWidgets.QLCDNumber(self.frame_3)
        self.Airspeed.setObjectName("Airspeed")
        self.gridLayout_3.addWidget(self.Airspeed, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.Longitude = QtWidgets.QLCDNumber(self.frame_3)
        self.Longitude.setObjectName("Longitude")
        self.gridLayout_3.addWidget(self.Longitude, 12, 0, 1, 1)
        self.Latitude = QtWidgets.QLCDNumber(self.frame_3)
        self.Latitude.setObjectName("Latitude")
        self.gridLayout_3.addWidget(self.Latitude, 10, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 11, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 9, 0, 1, 1)
        self.Altitude = QtWidgets.QLCDNumber(self.frame_3)
        self.Altitude.setObjectName("Altitude")
        self.gridLayout_3.addWidget(self.Altitude, 3, 0, 1, 1)
        self.PitchAngle = QtWidgets.QLCDNumber(self.frame_3)
        self.PitchAngle.setObjectName("PitchAngle")
        self.gridLayout_3.addWidget(self.PitchAngle, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 4, 0, 1, 1)
        self.RollAngle = QtWidgets.QLCDNumber(self.frame_3)
        self.RollAngle.setObjectName("RollAngle")
        self.gridLayout_3.addWidget(self.RollAngle, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(GroundStationSensorControl)
        self.label_9.setGeometry(QtCore.QRect(880, 420, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.frame.raise_()
        self.close.raise_()
        self.FPV_Feed.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.UAV_AT_Command_Line.raise_()
        self.label_7.raise_()
        self.Send_Commands.raise_()
        self.Command_Output.raise_()
        self.label_8.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.label_9.raise_()

        self.retranslateUi(GroundStationSensorControl)
        self.close.accepted.connect(GroundStationSensorControl.accept)
        self.close.rejected.connect(GroundStationSensorControl.reject)
        QtCore.QMetaObject.connectSlotsByName(GroundStationSensorControl)

    def retranslateUi(self, GroundStationSensorControl):
        _translate = QtCore.QCoreApplication.translate
        GroundStationSensorControl.setWindowTitle(_translate("GroundStationSensorControl", "GS Sensor Control Panel"))
        self.FPV_Feed.setToolTip(_translate("GroundStationSensorControl", "FPV Video Feed"))
        self.label.setText(_translate("GroundStationSensorControl", "Radio COM Port"))
        self.label_2.setText(_translate("GroundStationSensorControl", "Ground Station Sensor Control Panel"))
        self.label_7.setText(_translate("GroundStationSensorControl", "UAV AT Command Line"))
        self.EnableFPV.setText(_translate("GroundStationSensorControl", "Enable FPV Camera"))
        self.EnableDatalogging.setText(_translate("GroundStationSensorControl", "Enable Datalogging"))
        self.Send_Commands.setText(_translate("GroundStationSensorControl", "Send Commands"))
        self.label_8.setText(_translate("GroundStationSensorControl", "Toggle Options"))
        self.Connect_Radio.setText(_translate("GroundStationSensorControl", "Connect Radio"))
        self.Refresh_Ports.setText(_translate("GroundStationSensorControl", "Refresh Ports"))
        self.Airspeed.setToolTip(_translate("GroundStationSensorControl", "Meters Per Second"))
        self.label_4.setText(_translate("GroundStationSensorControl", "Altitude (Meters)"))
        self.Longitude.setToolTip(_translate("GroundStationSensorControl", "Lon - Decimal"))
        self.Latitude.setToolTip(_translate("GroundStationSensorControl", "Lat - Decimal"))
        self.label_6.setText(_translate("GroundStationSensorControl", "Longitude"))
        self.label_5.setText(_translate("GroundStationSensorControl", "Latitude"))
        self.Altitude.setToolTip(_translate("GroundStationSensorControl", "Meters"))
        self.PitchAngle.setToolTip(_translate("GroundStationSensorControl", "Lon - Decimal"))
        self.label_10.setText(_translate("GroundStationSensorControl", "Pitch Angle (Degrees)"))
        self.RollAngle.setToolTip(_translate("GroundStationSensorControl", "Lon - Decimal"))
        self.label_3.setText(_translate("GroundStationSensorControl", "Airspeed (m/s)"))
        self.label_11.setText(_translate("GroundStationSensorControl", "Roll Angle (Degrees)"))
        self.label_9.setText(_translate("GroundStationSensorControl", "Telemetry"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GroundStationSensorControl = QtWidgets.QDialog()
    ui = Ui_GroundStationSensorControl()
    ui.setupUi(GroundStationSensorControl)
    GroundStationSensorControl.show()
    sys.exit(app.exec_())
