# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GS_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroundStationSensorControl(object):
    def setupUi(self, GroundStationSensorControl):
        GroundStationSensorControl.setObjectName("GroundStationSensorControl")
        GroundStationSensorControl.resize(1894, 889)
        GroundStationSensorControl.setFocusPolicy(QtCore.Qt.WheelFocus)
        GroundStationSensorControl.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        GroundStationSensorControl.setAcceptDrops(False)
        GroundStationSensorControl.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(GroundStationSensorControl)
        self.buttonBox.setGeometry(QtCore.QRect(1690, 820, 131, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.FPV_Feed = QtWidgets.QLabel(GroundStationSensorControl)
        self.FPV_Feed.setGeometry(QtCore.QRect(30, 130, 831, 721))
        self.FPV_Feed.setFrameShape(QtWidgets.QFrame.Box)
        self.FPV_Feed.setMidLineWidth(4)
        self.FPV_Feed.setText("")
        self.FPV_Feed.setObjectName("FPV_Feed")
        self.COM_Select = QtWidgets.QComboBox(GroundStationSensorControl)
        self.COM_Select.setGeometry(QtCore.QRect(1090, 170, 191, 51))
        self.COM_Select.setObjectName("COM_Select")
        self.label = QtWidgets.QLabel(GroundStationSensorControl)
        self.label.setGeometry(QtCore.QRect(1090, 130, 311, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(GroundStationSensorControl)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 1251, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setLineWidth(3)
        self.label_2.setMidLineWidth(0)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(GroundStationSensorControl)
        self.label_3.setGeometry(QtCore.QRect(970, 410, 311, 31))
        self.label_3.setObjectName("label_3")
        self.Airspeed = QtWidgets.QLCDNumber(GroundStationSensorControl)
        self.Airspeed.setGeometry(QtCore.QRect(970, 450, 311, 41))
        self.Airspeed.setObjectName("Airspeed")
        self.label_4 = QtWidgets.QLabel(GroundStationSensorControl)
        self.label_4.setGeometry(QtCore.QRect(970, 530, 311, 31))
        self.label_4.setObjectName("label_4")
        self.Altitude = QtWidgets.QLCDNumber(GroundStationSensorControl)
        self.Altitude.setGeometry(QtCore.QRect(970, 570, 311, 41))
        self.Altitude.setObjectName("Altitude")
        self.label_5 = QtWidgets.QLabel(GroundStationSensorControl)
        self.label_5.setGeometry(QtCore.QRect(970, 650, 311, 31))
        self.label_5.setObjectName("label_5")
        self.Latitude = QtWidgets.QLCDNumber(GroundStationSensorControl)
        self.Latitude.setGeometry(QtCore.QRect(970, 690, 311, 41))
        self.Latitude.setObjectName("Latitude")
        self.label_6 = QtWidgets.QLabel(GroundStationSensorControl)
        self.label_6.setGeometry(QtCore.QRect(970, 770, 311, 31))
        self.label_6.setObjectName("label_6")
        self.Longitude = QtWidgets.QLCDNumber(GroundStationSensorControl)
        self.Longitude.setGeometry(QtCore.QRect(970, 810, 311, 41))
        self.Longitude.setObjectName("Longitude")
        self.Refresh_Ports = QtWidgets.QPushButton(GroundStationSensorControl)
        self.Refresh_Ports.setGeometry(QtCore.QRect(1090, 250, 191, 51))
        self.Refresh_Ports.setObjectName("Refresh_Ports")
        self.UAV_AT_Command_Line = QtWidgets.QLineEdit(GroundStationSensorControl)
        self.UAV_AT_Command_Line.setGeometry(QtCore.QRect(1310, 90, 551, 51))
        self.UAV_AT_Command_Line.setObjectName("UAV_AT_Command_Line")
        self.label_7 = QtWidgets.QLabel(GroundStationSensorControl)
        self.label_7.setGeometry(QtCore.QRect(1310, 50, 551, 31))
        self.label_7.setObjectName("label_7")
        self.frame = QtWidgets.QFrame(GroundStationSensorControl)
        self.frame.setGeometry(QtCore.QRect(880, 130, 181, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Sensor_Control_Only = QtWidgets.QRadioButton(self.frame)
        self.Sensor_Control_Only.setGeometry(QtCore.QRect(30, 110, 131, 61))
        self.Sensor_Control_Only.setToolTipDuration(-1)
        self.Sensor_Control_Only.setStatusTip("")
        self.Sensor_Control_Only.setObjectName("Sensor_Control_Only")
        self.Full_Pilot_Control = QtWidgets.QRadioButton(self.frame)
        self.Full_Pilot_Control.setGeometry(QtCore.QRect(30, 20, 131, 61))
        self.Full_Pilot_Control.setToolTipDuration(-1)
        self.Full_Pilot_Control.setStatusTip("")
        self.Full_Pilot_Control.setObjectName("Full_Pilot_Control")
        self.Send_Commands = QtWidgets.QPushButton(GroundStationSensorControl)
        self.Send_Commands.setGeometry(QtCore.QRect(1310, 170, 551, 51))
        self.Send_Commands.setObjectName("Send_Commands")
        self.Command_Output = QtWidgets.QTextEdit(GroundStationSensorControl)
        self.Command_Output.setGeometry(QtCore.QRect(1313, 250, 551, 541))
        self.Command_Output.setReadOnly(True)
        self.Command_Output.setObjectName("Command_Output")
        self.Connect_Radio = QtWidgets.QPushButton(GroundStationSensorControl)
        self.Connect_Radio.setGeometry(QtCore.QRect(1090, 330, 191, 51))
        self.Connect_Radio.setObjectName("Connect_Radio")
        self.frame.raise_()
        self.buttonBox.raise_()
        self.FPV_Feed.raise_()
        self.COM_Select.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.Airspeed.raise_()
        self.label_4.raise_()
        self.Altitude.raise_()
        self.label_5.raise_()
        self.Latitude.raise_()
        self.label_6.raise_()
        self.Longitude.raise_()
        self.Refresh_Ports.raise_()
        self.UAV_AT_Command_Line.raise_()
        self.label_7.raise_()
        self.Send_Commands.raise_()
        self.Command_Output.raise_()
        self.Connect_Radio.raise_()

        self.retranslateUi(GroundStationSensorControl)
        self.buttonBox.accepted.connect(GroundStationSensorControl.accept)
        self.buttonBox.rejected.connect(GroundStationSensorControl.reject)
        QtCore.QMetaObject.connectSlotsByName(GroundStationSensorControl)

    def retranslateUi(self, GroundStationSensorControl):
        _translate = QtCore.QCoreApplication.translate
        GroundStationSensorControl.setWindowTitle(_translate("GroundStationSensorControl", "GS Sensor Control Panel"))
        self.FPV_Feed.setToolTip(_translate("GroundStationSensorControl", "FPV Video Feed"))
        self.label.setText(_translate("GroundStationSensorControl", "Radio COM Port"))
        self.label_2.setText(_translate("GroundStationSensorControl", "Ground Station Sensor Control Panel"))
        self.label_3.setText(_translate("GroundStationSensorControl", "Airspeed (m/s)"))
        self.Airspeed.setToolTip(_translate("GroundStationSensorControl", "Meters Per Second"))
        self.label_4.setText(_translate("GroundStationSensorControl", "Altitude (Meters)"))
        self.Altitude.setToolTip(_translate("GroundStationSensorControl", "Meters"))
        self.label_5.setText(_translate("GroundStationSensorControl", "Latitude"))
        self.Latitude.setToolTip(_translate("GroundStationSensorControl", "Lat - Decimal"))
        self.label_6.setText(_translate("GroundStationSensorControl", "Longitude"))
        self.Longitude.setToolTip(_translate("GroundStationSensorControl", "Lon - Decimal"))
        self.Refresh_Ports.setText(_translate("GroundStationSensorControl", "Refresh Ports"))
        self.label_7.setText(_translate("GroundStationSensorControl", "UAV AT Command Line"))
        self.Sensor_Control_Only.setToolTip(_translate("GroundStationSensorControl", "Use joysticks to fly the UAV"))
        self.Sensor_Control_Only.setWhatsThis(_translate("GroundStationSensorControl", "Use joysticks to fly the UAV"))
        self.Sensor_Control_Only.setText(_translate("GroundStationSensorControl", "Sensor Control Only"))
        self.Full_Pilot_Control.setToolTip(_translate("GroundStationSensorControl", "Use joysticks to fly the UAV"))
        self.Full_Pilot_Control.setWhatsThis(_translate("GroundStationSensorControl", "Use joysticks to fly the UAV"))
        self.Full_Pilot_Control.setText(_translate("GroundStationSensorControl", "Full Pilot Controls"))
        self.Send_Commands.setText(_translate("GroundStationSensorControl", "Send Commands"))
        self.Connect_Radio.setText(_translate("GroundStationSensorControl", "Connect Radio"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GroundStationSensorControl = QtWidgets.QDialog()
    ui = Ui_GroundStationSensorControl()
    ui.setupUi(GroundStationSensorControl)
    GroundStationSensorControl.show()
    sys.exit(app.exec_())
